### ISSUE TITLE
Animation not working for latest version of Flutter and Dart

### ISSUE THREAD

**Issue by shahzans** [afgprogrammer/Flutter-Login-Signup-page#1]
Animation code is not working on the latest version of `Flutter 2.2.1` and `Dart 2.13.1`. Also, the latest version of the `simple_animations: ^3.1.1` package does not support the animation code.

Could you please fix this ASAP? Thanks in advance!

**Comment by afgprogrammer** [comment]
@shahzans check this https://pub.dev/packages/simple_animations

**Comment by shahzans** [comment]
@afgprogrammer As Salaam Alaikum Bro, Thanks for the reply. Are you available for freelance projects?

**Comment by afgprogrammer** [comment]
@shahzans wa alikum a salam bro, the issue section is not for the offering.
